# Generated by Django 4.1.3 on 2022-11-05 04:16

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaoDeObra',
            fields=[
                ('cargo', models.CharField(max_length=255)),
                ('contrato', models.CharField(max_length=255)),
                ('vinculo', models.CharField(max_length=255)),
                ('user', models.OneToOneField(default=builtins.id, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('contrato', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
